# DUA base units build and test configurations.
#
# Roberto Masocco <robmasocco@gmail.com>
# Intelligent Systems Lab <isl.torvergata@gmail.com>
#
# February 1, 2023

version: "3.9"

services:
  x86-base:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.x86-base
    image: intelligentsystemslabutv/dua-foundation:x86-base
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: bind
        source: ./
        target: /root/workspace

  x86-dev:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.x86-dev
    image: intelligentsystemslabutv/dua-foundation:x86-dev
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: bind
        source: ./
        target: /root/workspace

  x86-cudev:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.x86-cudev
    image: intelligentsystemslabutv/dua-foundation:x86-cudev
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: bind
        source: ./
        target: /root/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  armv8-jetson5c7-base:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.armv8-jetson5c7-base
      args:
        - DUA_UTILS_VERSION=20230304-1247
    image: intelligentsystemslabutv/dua-foundation:armv8-jetson5c7-base
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/jtop.sock:/run/jtop.sock
      - type: bind
        source: ./
        target: /root/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
