# DUA base units build and test configurations.
#
# Roberto Masocco <robmasocco@gmail.com>
# Intelligent Systems Lab <isl.torvergata@gmail.com>
#
# February 1, 2023

version: "3.9"

services:
  x86-base:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.x86-base
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:x86-base
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/root/workspace

  x86-dev:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.x86-dev
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:x86-dev
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/root/workspace

  x86-cudev:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.x86-cudev
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:x86-cudev
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/root/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  armv8-base:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.armv8-base
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:armv8-base
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/root/workspace

  armv8-dev:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.armv8-dev
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:armv8-dev
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/root/workspace

  jetson5c7:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.jetson5c7
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:jetson5c7
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/jtop.sock:/run/jtop.sock
      - ./:/root/workspace

  jetson4c5:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.jetson4c5
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:jetson4c5
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/jtop.sock:/run/jtop.sock
      - ./:/root/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  jetson4c6:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.jetson4c6
      args:
        - DUA_UTILS_VERSION=20230611-1845
    image: intelligentsystemslabutv/dua-foundation:jetson4c6
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    privileged: true
    ipc: host
    stdin_open: false
    tty: true
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/root/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/jtop.sock:/run/jtop.sock
      - ./:/root/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
